#!/bin/bash

#DEBHELPER#

# preinst script for virtualbox-guest-utils-modified-init

#set -e

if [ -e /etc/init.d/virtualbox-guest-utils ]; then
    mv /etc/init.d/virtualbox-guest-utils /etc/init.d/virtualbox-guest-utils-VB_MOD-$(date +%Y%m%H%M%S).dpkg-distrib
fi

case "$1" in
  install|upgrade) dpkg-divert --quiet                                               \
                               --add                                                 \
                               --package virtualbox-guest-utils-modified-init            \
                               --rename                              \
                               --divert /etc/init.d/virtualbox-guest-utils.dpkg-distrib \
                               /etc/init.d/virtualbox-guest-utils
                   ;;

                *) :
                   ;;
esac 

exit 0
